# The configuration for the python build in Logging module
version: 1

formatters:
  brief:
    format: "%(asctime)s|%(funcName)s|%(levelname)s: %(message)s"
    datefmt: "%d-%m-%yT%H-%M-%S"
    validate: true
  verbose:
    format: "[%(asctime)s|%(module)s/%(funcName)s:%(lineno)d -> %(levelname)s]: %(message)s"
    datefmt: "%d-%m-%yT%H-%M-%S"
    validate: true

handlers:
  console:
    class: "logging.StreamHandler"
    formatter: "brief"
    level: "INFO"
    stream: "ext://sys.stdout"

loggers:
  main:
    handlers:
      - "console"
    level: "DEBUG"

